import Navigation from "@/components/pizza-menu-components/header";
import CartOverview from "./cart/CartOverview";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <div className="flex h-screen flex-col">
      <Navigation />
      {children}
      <CartOverview />
    </div>
  );
}
