import "./globals.css";
import Navigation from "@/ui/pizza-menu/header";
import CartOverview from "./pizza-app/cart/CartOverview";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex h-screen flex-col">
        <Navigation />
        {children}
        <CartOverview />
      </body>
    </html>
  );
}
